version: '3.8'

services:
  web:
    build: .
    container_name: task-api
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///tasks.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

